[runner]
fastReruns = true

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

# Forzar versión de Python compatible
[python]
version = "3.10"
